{
  "comments": [
    {
      "key": {
        "uuid": "7ad507d5_f188188c",
        "filename": "tests/api/v1/test_issues.py",
        "patchSetId": 6
      },
      "lineNbr": 404,
      "author": {
        "id": 405
      },
      "writtenOn": "2018-11-22T14:00:17Z",
      "side": 1,
      "message": "3 tests are easy to debug in case of failure",
      "range": {
        "startLine": 379,
        "startChar": 0,
        "endLine": 404,
        "endChar": 47
      },
      "revId": "521d0e66ee33f1699d7adec41a4a09099219b5d1",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    }
  ]
}