{
  "comments": [
    {
      "key": {
        "uuid": "7a016987_a60e86e3",
        "filename": "dci/api/v1/remotecis.py",
        "patchSetId": 3
      },
      "lineNbr": 211,
      "author": {
        "id": 115
      },
      "writtenOn": "2018-02-05T08:56:58Z",
      "side": 1,
      "message": "If I am not mistaken, this whole change could be simplified by:\n\nif not user.is_member_of(remoteci[\u0027team_id\u0027]):\n    raise auth.UNAUTHORIZED",
      "revId": "7a22c7f6aca1205702a3a4bd288548a4723a734e",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    }
  ]
}